### PR TITLE
Brittrich feature/dept directory styles

### PR DESCRIPTION
**Pull request by bmartinez287**
Here is take two. Merges the upstream dist directory to resolves any conflict.
I think this resolves the conflict and it removes the upstream dist directory.
git checkout upstream/develop dist
That's the command I use to reset my dist folder to what is on the upstream branch.
I think all your changes are preserved in this commit.
If they are go ahead and merge into yours. @brittrich

### CODE REVIEW

**Comment by bmartinez287** [comment]
The first one I close the first one is because I did against your develop branch which should be avoided as you pull that one from upstream. This one got into the PR that you had open already. 
Once this is merge the changes should be reflected here.
https://github.com/brittrich/particle/tree/feature/dept-directory-styles which should update this PR automatically https://github.com/UTCWeb/particle/pull/183

**Comment by brittrich** [comment]
> The first one I close the first one is because I did against your develop branch which should be avoided as you pull that one from upstream. This one got into the PR that you had open already.
> Once this is merge the changes should be reflected here.
> https://github.com/brittrich/particle/tree/feature/dept-directory-styles which should update this PR automatically [UTCWeb#183](https://github.com/UTCWeb/particle/pull/183)

@bmartinez287 Just to make sure I'm tracking, I don't see any of the files I actually changes in this PR. But, maybe that doesn't matter because the point is that it is preserving some recent develop file changes from other folks and removing the /dist file changes?

**Comment by bmartinez287** [comment]
what's the file path of the documents you changed? Where those in the dist folder file path? If they are then it does not matter. If they are not then it matters.
For those files that are missing can you add the file path here?

**Comment by brittrich** [comment]
> what's the file path of the documents you changed? Where those in the dist folder file path? If they are then it does not matter. If they are not then it matters.
> For those files that are missing can you add the file path here?

Honestly, this is the only one I want to be sure to preserve at this point.
...l-default/particle_theme/templates/views/views-view-table--department-directory.html.twig

I realized I need to make the other changes in a different way (e.g. form labels) to avoid issues in other spots.

Let me know if it's easiest for me to just create a new branch and copy this file over and do a new PR. Really, happy to do that if it saves you time having to troubleshoot.

**Comment by bmartinez287** [comment]
So after looking at it, it seems like this repo has your changes. 
https://github.com/bmartinez287/particle/blob/brittrich-feature/dept-directory-styles/apps/drupal-default/particle_theme/templates/views/views-view-table--department-directory.html.twig
It's tricky to see it, because this PR is only reflecting changes made that were partials and not complete ones. The easiest way to tell is to merge it. Save the file on a different folder just in case and check after is merged if it got affected by it.
I think this PR should preserve your changes but just in case.

**Comment by bmartinez287** [comment]
I one of those git magic items. @brittrich

**Pull request merged**
